export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'

export const TOGGLE_NAV = 'TOGGLE_NAV'

export const DATA_FETCHING = 'DATA_FETCHING'

export const GET_BOOKING_LIST_SUCCESS = 'GET_BOOKING_LIST_SUCCESS'

export const GET_BOOKING_SUCCESS = 'GET_BOOKING_SUCCESS'
